services:
    php:
        image: tugboatqa/php:7.1-apache
        default: true
        depends: mysql
        commands:
            init:
                - composer --no-ansi global require drush/drush
                - ln -sf ~/.composer/vendor/bin/drush /usr/local/bin/drush
                - ln -snf "${TUGBOAT_ROOT}/docroot" "${DOCROOT}"
                - cp "${DOCROOT}/sites/default/settings.tugboat.php" "${DOCROOT}/sites/default/settings.local.php"
            update:
                - curl -L "https://www.dropbox.com/s/gsiqvw8g3rlu86e/demo-drupal7-files.tar.gz?dl=0" > /tmp/files.tar.gz
                - tar -C /tmp -zxf /tmp/files.tar.gz
                - rsync -av --delete /tmp/files/ /var/www/html/sites/default/files/
                - rm -rf /tmp/files /tmp/files.tar.gz
            build:
                - drush -r "${DOCROOT}" cache-clear all

    mysql:
        image: tugboatqa/mysql
        commands:
            update:
                - curl -L "https://www.dropbox.com/s/avmxy5bn0tza3ag/demo-drupal7-database.sql.gz?dl=0" > /tmp/database.sql.gz
                - zcat /tmp/database.sql.gz | mysql tugboat
                - rm /tmp/database.sql.gz
